version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      maven:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/frontend"
      - "/e2e"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/mocks/mock-server"
      - "/pdfgen"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "/mocks/mock-oidc"
      - "/mocks/mock-server"
      - "/pdfgen"
    schedule:
      interval: "weekly"
    groups:
      docker-compose:
        patterns:
          - "*"
