<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>no.nav.historisk</groupId>
    <artifactId>superhelt-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>superhelt-parent</name>
    <description>Saksbehandling og Utbetaling På Enkle Regler</description>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <java.version>25</java.version>
        <springdoc.version>3.1.1</springdoc.version>

        <!-- Diverse overstyringer av spring boot avhengigheter. Bør fjernes når spring boot kommer med nye versjoner -->
        <!--  midlertidig fix for CVE-2026-65182 -->
        <tomcat.version>11.0.26</tomcat.version>
        <!--  midlertidig fix for CVE-2026-19880 -->
        <logback.version>1.6.5</logback.version>
        <!--  midlertidig fix for diverse jackson feil -->
        <jackson-2-bom.version>2.21.7</jackson-2-bom.version>
        <jackson-bom.version>3.1.7</jackson-bom.version>
        <!--  midlertidig fix for diverse kafka feil -->
        <kafka.version>4.2.2</kafka.version>
    </properties>
    <modules>
        <module>libs</module>
        <module>frontend</module>
        <module>mocks</module>
        <module>backend</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
