/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param ident 
 * @param type 
 */


data class BrukerDto (

    @get:JsonProperty("ident")
    val ident: kotlin.String? = null,

    @get:JsonProperty("type")
    val type: BrukerDto.Type? = null

) {

    /**
     * 
     *
     * Values: PERSON,ARBEIDSGIVER,SAMHANDLER
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "PERSON") PERSON("PERSON"),
        @JsonProperty(value = "ARBEIDSGIVER") ARBEIDSGIVER("ARBEIDSGIVER"),
        @JsonProperty(value = "SAMHANDLER") SAMHANDLER("SAMHANDLER");
    }

}

