/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param uuid 
 * @param feilmelding 
 */


data class ErrorResponse (

    @get:JsonProperty("uuid")
    val uuid: kotlin.String? = null,

    @get:JsonProperty("feilmelding")
    val feilmelding: kotlin.String? = null

) {


}

