/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param behandlingstema 
 * @param behandlingstemaTerm 
 * @param behandlingstype 
 * @param behandlingstypeTerm 
 */


data class Gjelder (

    @get:JsonProperty("behandlingstema")
    val behandlingstema: kotlin.String? = null,

    @get:JsonProperty("behandlingstemaTerm")
    val behandlingstemaTerm: kotlin.String? = null,

    @get:JsonProperty("behandlingstype")
    val behandlingstype: kotlin.String? = null,

    @get:JsonProperty("behandlingstypeTerm")
    val behandlingstypeTerm: kotlin.String? = null

) {


}

