/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param oppgaveId 
 * @param utfortAv 
 * @param tildeltEnhetsnr 
 * @param mappeId 
 * @param tilordnetRessurs 
 * @param status 
 * @param tema 
 * @param oppgavetype 
 * @param tidspunkt 
 * @param utfortAvEnhetsnr 
 * @param hendelsestype 
 * @param behandlingstema 
 * @param behandlingstype 
 * @param fristFerdigstillelse 
 * @param aktivDato 
 * @param prioritet 
 * @param journalpostId 
 * @param saksreferanse 
 * @param utfortFraSystem 
 */


data class HendelseJson (

    @get:JsonProperty("oppgaveId")
    val oppgaveId: kotlin.Long? = null,

    @get:JsonProperty("utfortAv")
    val utfortAv: kotlin.String? = null,

    @get:JsonProperty("tildeltEnhetsnr")
    val tildeltEnhetsnr: kotlin.String? = null,

    @get:JsonProperty("mappeId")
    val mappeId: kotlin.Long? = null,

    @get:JsonProperty("tilordnetRessurs")
    val tilordnetRessurs: kotlin.String? = null,

    @get:JsonProperty("status")
    val status: kotlin.String? = null,

    @get:JsonProperty("tema")
    val tema: kotlin.String? = null,

    @get:JsonProperty("oppgavetype")
    val oppgavetype: kotlin.String? = null,

    @get:JsonProperty("tidspunkt")
    val tidspunkt: java.time.OffsetDateTime? = null,

    @get:JsonProperty("utfortAvEnhetsnr")
    val utfortAvEnhetsnr: kotlin.String? = null,

    @get:JsonProperty("hendelsestype")
    val hendelsestype: HendelseJson.Hendelsestype? = null,

    @get:JsonProperty("behandlingstema")
    val behandlingstema: kotlin.String? = null,

    @get:JsonProperty("behandlingstype")
    val behandlingstype: kotlin.String? = null,

    @get:JsonProperty("fristFerdigstillelse")
    val fristFerdigstillelse: java.time.LocalDate? = null,

    @get:JsonProperty("aktivDato")
    val aktivDato: java.time.LocalDate? = null,

    @get:JsonProperty("prioritet")
    val prioritet: HendelseJson.Prioritet? = null,

    @get:JsonProperty("journalpostId")
    val journalpostId: kotlin.String? = null,

    @get:JsonProperty("saksreferanse")
    val saksreferanse: kotlin.String? = null,

    @get:JsonProperty("utfortFraSystem")
    val utfortFraSystem: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: OPPGAVE_OPPRETTET,OPPGAVE_ENDRET,OPPGAVE_FERDIGSTILT,OPPGAVE_FEILREGISTRERT
     */
    enum class Hendelsestype(val value: kotlin.String) {
        @JsonProperty(value = "OPPGAVE_OPPRETTET") OPPGAVE_OPPRETTET("OPPGAVE_OPPRETTET"),
        @JsonProperty(value = "OPPGAVE_ENDRET") OPPGAVE_ENDRET("OPPGAVE_ENDRET"),
        @JsonProperty(value = "OPPGAVE_FERDIGSTILT") OPPGAVE_FERDIGSTILT("OPPGAVE_FERDIGSTILT"),
        @JsonProperty(value = "OPPGAVE_FEILREGISTRERT") OPPGAVE_FEILREGISTRERT("OPPGAVE_FEILREGISTRERT");
    }
    /**
     * 
     *
     * Values: HOY,NORM,LAV
     */
    enum class Prioritet(val value: kotlin.String) {
        @JsonProperty(value = "HOY") HOY("HOY"),
        @JsonProperty(value = "NORM") NORM("NORM"),
        @JsonProperty(value = "LAV") LAV("LAV");
    }

}

