/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param antallTreffTotalt Totalt antall mapper funnet med dette søket
 * @param mapper Liste over mapper
 */


data class HentMapperResponse (

    /* Totalt antall mapper funnet med dette søket */
    @get:JsonProperty("antallTreffTotalt")
    val antallTreffTotalt: kotlin.Long? = null,

    /* Liste over mapper */
    @get:JsonProperty("mapper")
    val mapper: kotlin.collections.List<Mappe>? = null

) {


}

