/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tema 
 * @param oppgavetype 
 * @param behandlingstema 
 * @param behandlingstype 
 */


data class Kategorisering (

    @get:JsonProperty("tema")
    val tema: Kodeverkskode? = null,

    @get:JsonProperty("oppgavetype")
    val oppgavetype: Kodeverkskode? = null,

    @get:JsonProperty("behandlingstema")
    val behandlingstema: NullbarKodeverkskode? = null,

    @get:JsonProperty("behandlingstype")
    val behandlingstype: NullbarKodeverkskode? = null

) {


}

