/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tema 
 * @param oppgavetype 
 * @param kategorisering 
 * @param nokkelord 
 * @param mappe 
 * @param prioritet 
 * @param frist 
 * @param opprettet 
 * @param identStartsWith 
 */


data class Koefilter (

    @get:JsonProperty("tema")
    val tema: kotlin.collections.Set<Kodeverkskode>? = null,

    @get:JsonProperty("oppgavetype")
    val oppgavetype: kotlin.collections.Set<Kodeverkskode>? = null,

    @get:JsonProperty("kategorisering")
    val kategorisering: kotlin.collections.Set<Kategorisering>? = null,

    @get:JsonProperty("nokkelord")
    val nokkelord: kotlin.collections.Set<kotlin.String>? = null,

    @get:JsonProperty("mappe")
    val mappe: kotlin.collections.Set<IdKriterie>? = null,

    @get:JsonProperty("prioritet")
    val prioritet: kotlin.collections.Set<Koefilter.Prioritet>? = null,

    @get:JsonProperty("frist")
    val frist: Periode? = null,

    @get:JsonProperty("opprettet")
    val opprettet: Periode? = null,

    @get:JsonProperty("identStartsWith")
    val identStartsWith: kotlin.collections.Set<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: LAV,NORMAL,HOY
     */
    enum class Prioritet(val value: kotlin.String) {
        @JsonProperty(value = "LAV") LAV("LAV"),
        @JsonProperty(value = "NORMAL") NORMAL("NORMAL"),
        @JsonProperty(value = "HOY") HOY("HOY");
    }

}

