/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param koefilter 
 * @param sortering 
 * @param antallOppgaver 
 * @param tildelingskriterie 
 */


data class Koekriterier (

    @get:JsonProperty("koefilter")
    val koefilter: Koefilter? = null,

    @get:JsonProperty("sortering")
    val sortering: Sortering? = null,

    @get:JsonProperty("antallOppgaver")
    val antallOppgaver: kotlin.Long? = null,

    @get:JsonProperty("tildelingskriterie")
    val tildelingskriterie: Koekriterier.Tildelingskriterie? = null

) {

    /**
     * 
     *
     * Values: PRIORITERT_REKKEFOLGE,GEOGRAFI,BRUKER
     */
    enum class Tildelingskriterie(val value: kotlin.String) {
        @JsonProperty(value = "PRIORITERT_REKKEFOLGE") PRIORITERT_REKKEFOLGE("PRIORITERT_REKKEFOLGE"),
        @JsonProperty(value = "GEOGRAFI") GEOGRAFI("GEOGRAFI"),
        @JsonProperty(value = "BRUKER") BRUKER("BRUKER");
    }

}

