/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param tekst 
 * @param registrertAv 
 * @param registrertAvEnhet 
 * @param registrertAvSystem 
 * @param registrertTidspunkt 
 * @param legacy 
 */


data class KommentarJson (

    @get:JsonProperty("tekst")
    val tekst: kotlin.String? = null,

    @get:JsonProperty("registrertAv")
    val registrertAv: kotlin.String? = null,

    @get:JsonProperty("registrertAvEnhet")
    val registrertAvEnhet: kotlin.String? = null,

    @get:JsonProperty("registrertAvSystem")
    val registrertAvSystem: kotlin.String? = null,

    @get:JsonProperty("registrertTidspunkt")
    val registrertTidspunkt: java.time.OffsetDateTime? = null,

    @get:JsonProperty("legacy")
    val legacy: kotlin.Boolean? = null

) {


}

