/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param enhetsnr Enheten mappen hører til
 * @param navn Mappenavn eller beskrivelse
 * @param versjon Brukes for å håndtere optimistisk låsing, hvor to brukere har skrevet på samme mappe. Hver gang det gjøres endring på en mappe, økes verdien av VERSJON med 1. Når en klient skal lagre til på en mappe, sendes verdien av VERSJON mappen hadde da informasjon om mappen som nå er endret ble hentet ut. Dersom verdien av VERSJON er endret, har noen andre lagret mappen i mellomtiden, og mappen kan ikke lagres. 409 Conflict vil returneres fra tjenesten. Under oppretting av mappe trenger man ikke å spesifisere noen verdi for dette feltet, mappen vil starte på versjon 1
 * @param id Syntetisk id
 * @param tema Tema slik den er definert i felles kodeverk
 * @param opprettetAv Hvilken bruker eller system som opprettet mappen
 * @param endretAv Hvilken bruker eller system som endret mappen sist
 * @param opprettetTidspunkt Opprettet tidspunkt iht. ISO-8601
 * @param endretTidspunkt Endret tidspunkt iht. ISO-8601
 */


data class Mappe (

    /* Enheten mappen hører til */
    @get:JsonProperty("enhetsnr")
    val enhetsnr: kotlin.String,

    /* Mappenavn eller beskrivelse */
    @get:JsonProperty("navn")
    val navn: kotlin.String,

    /* Brukes for å håndtere optimistisk låsing, hvor to brukere har skrevet på samme mappe. Hver gang det gjøres endring på en mappe, økes verdien av VERSJON med 1. Når en klient skal lagre til på en mappe, sendes verdien av VERSJON mappen hadde da informasjon om mappen som nå er endret ble hentet ut. Dersom verdien av VERSJON er endret, har noen andre lagret mappen i mellomtiden, og mappen kan ikke lagres. 409 Conflict vil returneres fra tjenesten. Under oppretting av mappe trenger man ikke å spesifisere noen verdi for dette feltet, mappen vil starte på versjon 1 */
    @get:JsonProperty("versjon")
    val versjon: kotlin.Int,

    /* Syntetisk id */
    @get:JsonProperty("id")
    val id: kotlin.Long? = null,

    /* Tema slik den er definert i felles kodeverk */
    @get:JsonProperty("tema")
    val tema: kotlin.String? = null,

    /* Hvilken bruker eller system som opprettet mappen */
    @get:JsonProperty("opprettetAv")
    val opprettetAv: kotlin.String? = null,

    /* Hvilken bruker eller system som endret mappen sist */
    @get:JsonProperty("endretAv")
    val endretAv: kotlin.String? = null,

    /* Opprettet tidspunkt iht. ISO-8601 */
    @get:JsonProperty("opprettetTidspunkt")
    val opprettetTidspunkt: java.time.OffsetDateTime? = null,

    /* Endret tidspunkt iht. ISO-8601 */
    @get:JsonProperty("endretTidspunkt")
    val endretTidspunkt: java.time.OffsetDateTime? = null

) {


}

