/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param kode 
 */


data class NullbarKodeverkskode (

    @get:JsonProperty("kode")
    val kode: kotlin.String? = null

) {


}

