/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param oppgavetype 
 * @param term 
 */


data class Oppgavetype (

    @get:JsonProperty("oppgavetype")
    val oppgavetype: kotlin.String,

    @get:JsonProperty("term")
    val term: kotlin.String

) {


}

