/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param filter 
 * @param paginering 
 * @param sortering 
 */


data class Oppgavesok (

    @get:JsonProperty("filter")
    val filter: Filter? = null,

    @get:JsonProperty("paginering")
    val paginering: Paginering? = null,

    @get:JsonProperty("sortering")
    val sortering: Sortering? = null

) {


}

