/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param antall 
 * @param nestePeker 
 */


data class Paginering (

    @get:JsonProperty("antall")
    val antall: kotlin.Int? = null,

    @get:JsonProperty("nestePeker")
    val nestePeker: kotlin.String? = null

) {


}

