/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param fra 
 * @param til 
 */


data class Periode (

    @get:JsonProperty("fra")
    val fra: java.time.LocalDate? = null,

    @get:JsonProperty("til")
    val til: java.time.LocalDate? = null

) {


}

