/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param oppgaveIder 
 */


data class PubliserKafkahendelserRequest (

    @get:JsonProperty("oppgaveIder")
    val oppgaveIder: kotlin.collections.List<kotlin.Long>? = null

) {


}

