/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Kommentar i tilknytning til endringer. Hensyntas kun ved patch
 *
 * @param tekst 
 * @param automatiskGenerert Skal settes til true dersom kommentaren er automatisk generert av et system, og det benyttes OBO-token. Ignoreres ved CCF
 */


data class RegistrerKommentarJson (

    @get:JsonProperty("tekst")
    val tekst: kotlin.String? = null,

    /* Skal settes til true dersom kommentaren er automatisk generert av et system, og det benyttes OBO-token. Ignoreres ved CCF */
    @get:JsonProperty("automatiskGenerert")
    val automatiskGenerert: kotlin.Boolean? = null

) {


}

