/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param antallTreffTotalt Totalt antall oppgaver funnet med dette søket
 * @param oppgaver Liste over oppgaver
 */


data class SokOppgaverResponse (

    /* Totalt antall oppgaver funnet med dette søket */
    @get:JsonProperty("antallTreffTotalt")
    val antallTreffTotalt: kotlin.Long? = null,

    /* Liste over oppgaver */
    @get:JsonProperty("oppgaver")
    val oppgaver: kotlin.collections.List<Oppgave>? = null

) {


}

