/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.nav.oppgave.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param felt 
 * @param rekkefolge 
 */


data class Sortering (

    @get:JsonProperty("felt")
    val felt: Sortering.Felt? = null,

    @get:JsonProperty("rekkefolge")
    val rekkefolge: Sortering.Rekkefolge? = null

) {

    /**
     * 
     *
     * Values: FRIST,OPPRETTET
     */
    enum class Felt(val value: kotlin.String) {
        @JsonProperty(value = "FRIST") FRIST("FRIST"),
        @JsonProperty(value = "OPPRETTET") OPPRETTET("OPPRETTET");
    }
    /**
     * 
     *
     * Values: ELDSTE_FORST,NYESTE_FORST
     */
    enum class Rekkefolge(val value: kotlin.String) {
        @JsonProperty(value = "ELDSTE_FORST") ELDSTE_FORST("ELDSTE_FORST"),
        @JsonProperty(value = "NYESTE_FORST") NYESTE_FORST("NYESTE_FORST");
    }

}

