apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: superhelt
  namespace: historisk
  labels:
    team: historisk
spec:
  image: "{{image}}"
  port: 8080
  kafka:
    pool: nav-{{env}}
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: {{gruppe.saksbehandler}}
          - id: {{gruppe.attestant}}
          - id: {{gruppe.les}}

  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
  strategy:
    type: RollingUpdate
  replicas:
    min: 1
    max: 1

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - {{appIngress}}

  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk

  accessPolicy:
    outbound:
      rules:
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
        - application: historisk-pdfgen
      external:
        - host: "pdl-api.{{env}}-fss-pub.nais.io"
        - host: "oppgave.{{env}}-fss-pub.nais.io"
        - host: "dokarkiv{{legacyEnvSuffix}}.{{env}}-fss-pub.nais.io"
        - host: "dokdistfordeling.{{env}}-fss-pub.nais.io"
        - host: "saf{{legacyEnvSuffix}}.{{env}}-fss-pub.nais.io"

  env:
    - name: APP_FNR_ENCRYPTOR_SECRET
      value: "{{env}}-encryptor-superhelt-fnr"
    - name: APP_GRUPPE_SAKSBEHANDLER
      value: "{{gruppe.saksbehandler}}"
    - name: APP_GRUPPE_ATTESTANT
      value: "{{gruppe.attestant}}"
    - name: APP_GRUPPE_LES
      value: "{{gruppe.les}}"
    - name: APP_PDL_URL
      value: https://pdl-api.{{env}}-fss-pub.nais.io
    - name: APP_PDL_AUDIENCE
      value: api://{{env}}-fss.pdl.pdl-api/.default
    - name: APP_TILGANGSMASKIN_URL
      value: "http://populasjonstilgangskontroll.tilgangsmaskin"
    - name: APP_TILGANGSMASKIN_AUDIENCE
      value: "api://{{env}}-gcp.tilgangsmaskin.populasjonstilgangskontroll/.default"
    - name: APP_PDFGEN_URL
      value: "http://historisk-pdfgen"


