apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: utbetaling.v1
  namespace: historisk
  labels:
    team: historisk
spec:
  pool: nav-{{env}}
  acl:
    - team: historisk
      application: superhelt
      access: readwrite
    - team: helved
      application: abetal
      access: read
    - team: helved
      application: peisschtappern
      access: read

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  # todo rette opp navn når vi det er testet
  name: superhelt.statistikk.saksbehandling.test
  namespace: historisk
  labels:
    team: historisk
spec:
  pool: nav-{{env}}
  config:
    retentionHours: 720
  acl:
    - team: historisk
      application: superhelt
      access: readwrite
    - team: ptsak
      application: pt-sak-superhelt
      access: read