// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type SakCreateRequestDto = {
    type: 'PARYKK' | 'ORTOSE' | 'PROTESE' | 'FOTTOY' | 'REISEUTGIFTER';
    person: string;
    tittel?: string;
    begrunnelse?: string;
};

export type SakDto = {
    saksnummer: string;
    type: 'PARYKK' | 'ORTOSE' | 'PROTESE' | 'FOTTOY' | 'REISEUTGIFTER';
    person: string;
    tittel?: string;
    begrunnelse?: string;
    status: 'UNDER_BEHANDLING' | 'TIL_ATTESTERING' | 'FERDIG_BEHANDLET';
    vedtak?: 'INNVILGET' | 'AVSLATT' | 'DELVIS_INNVILGET' | 'HENLAGT';
};

export type PersonRequest = {
    fnr: string;
};

export type Person = {
    navn: string;
    fnr: string;
    maskertPersonident: string;
    doed: boolean;
    adressebeskyttelseGradering?: 'FORTROLIG' | 'STRENGT_FORTROLIG' | 'STRENGT_FORTROLIG_UTLAND' | 'UGRADERT';
    verge: boolean;
    avvisningsKode?: 'AVVIST_STRENGT_FORTROLIG_ADRESSE' | 'AVVIST_STRENGT_FORTROLIG_UTLAND' | 'AVVIST_AVDØD' | 'AVVIST_PERSON_UTLAND' | 'AVVIST_SKJERMING' | 'AVVIST_FORTROLIG_ADRESSE' | 'AVVIST_UKJENT_BOSTED' | 'AVVIST_GEOGRAFISK' | 'AVVIST_HABILITET' | 'UKJENT_PERSON';
    avvisningsBegrunnelse?: string;
};

export type User = {
    name: string;
    roles: Array<'LES' | 'SAKSBEHANDLER' | 'ATTESTANT'>;
};

export type FindSakerData = {
    body?: never;
    path?: never;
    query: {
        maskertPersonId: string;
    };
    url: '/api/sak';
};

export type FindSakerErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type FindSakerError = FindSakerErrors[keyof FindSakerErrors];

export type FindSakerResponses = {
    /**
     * OK
     */
    200: Array<SakDto>;
};

export type FindSakerResponse = FindSakerResponses[keyof FindSakerResponses];

export type CreateSakData = {
    body: SakCreateRequestDto;
    path?: never;
    query?: never;
    url: '/api/sak';
};

export type CreateSakErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type CreateSakError = CreateSakErrors[keyof CreateSakErrors];

export type CreateSakResponses = {
    /**
     * OK
     */
    200: SakDto;
};

export type CreateSakResponse = CreateSakResponses[keyof CreateSakResponses];

export type FindPersonData = {
    body: PersonRequest;
    path?: never;
    query?: never;
    url: '/api/person/';
};

export type FindPersonErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type FindPersonError = FindPersonErrors[keyof FindPersonErrors];

export type FindPersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type FindPersonResponse = FindPersonResponses[keyof FindPersonResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetUserInfoErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetSakBySaksnummerData = {
    body?: never;
    path: {
        saksnummer: string;
    };
    query?: never;
    url: '/api/sak/{saksnummer}';
};

export type GetSakBySaksnummerErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetSakBySaksnummerError = GetSakBySaksnummerErrors[keyof GetSakBySaksnummerErrors];

export type GetSakBySaksnummerResponses = {
    /**
     * OK
     */
    200: SakDto;
};

export type GetSakBySaksnummerResponse = GetSakBySaksnummerResponses[keyof GetSakBySaksnummerResponses];

export type GetPersonData = {
    body?: never;
    path: {
        maskertPersonident: string;
    };
    query?: never;
    url: '/api/person/{maskertPersonident}';
};

export type GetPersonErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetail;
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetPersonError = GetPersonErrors[keyof GetPersonErrors];

export type GetPersonResponses = {
    /**
     * OK
     */
    200: Person;
};

export type GetPersonResponse = GetPersonResponses[keyof GetPersonResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};