// This file is auto-generated by @hey-api/openapi-ts

export type ProblemDetail = {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type SakCreateRequestDto = {
    type: 'PARYKK' | 'ORTOSE' | 'PROTESE' | 'FOTTOY' | 'REISEUTGIFTER';
    person: string;
    tittel?: string;
    begrunnelse?: string;
};

export type SakDto = {
    saksnummer: string;
    type: 'PARYKK' | 'ORTOSE' | 'PROTESE' | 'FOTTOY' | 'REISEUTGIFTER';
    person: string;
    tittel?: string;
    begrunnelse?: string;
    status: 'UNDER_BEHANDLING' | 'TIL_ATTESTERING' | 'FERDIG_BEHANDLET';
    vedtak?: 'INNVILGET' | 'AVSLATT' | 'DELVIS_INNVILGET' | 'HENLAGT';
};

export type PersonRequest = {
    fnr: string;
};

export type Person = {
    navn: string;
    fnr: string;
    maskertPersonident: string;
    doed: boolean;
    adressebeskyttelseGradering: 'FORTROLIG' | 'STRENGT_FORTROLIG' | 'STRENGT_FORTROLIG_UTLAND' | 'UGRADERT';
    verge: boolean;
};

export type User = {
    name: string;
    roles: Array<string>;
};

export type GetAllSakerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sak';
};

export type GetAllSakerErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetAllSakerError = GetAllSakerErrors[keyof GetAllSakerErrors];

export type GetAllSakerResponses = {
    /**
     * OK
     */
    200: Array<SakDto>;
};

export type GetAllSakerResponse = GetAllSakerResponses[keyof GetAllSakerResponses];

export type CreateSakData = {
    body: SakCreateRequestDto;
    path?: never;
    query?: never;
    url: '/api/sak';
};

export type CreateSakErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type CreateSakError = CreateSakErrors[keyof CreateSakErrors];

export type CreateSakResponses = {
    /**
     * OK
     */
    200: SakDto;
};

export type CreateSakResponse = CreateSakResponses[keyof CreateSakResponses];

export type HentPersondataMedPersonidentData = {
    body: PersonRequest;
    path?: never;
    query?: never;
    url: '/api/person/';
};

export type HentPersondataMedPersonidentErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type HentPersondataMedPersonidentError = HentPersondataMedPersonidentErrors[keyof HentPersondataMedPersonidentErrors];

export type HentPersondataMedPersonidentResponses = {
    /**
     * OK
     */
    200: Person;
};

export type HentPersondataMedPersonidentResponse = HentPersondataMedPersonidentResponses[keyof HentPersondataMedPersonidentResponses];

export type GetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user';
};

export type GetUserInfoErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetUserInfoError = GetUserInfoErrors[keyof GetUserInfoErrors];

export type GetUserInfoResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type GetSakBySaksnummerData = {
    body?: never;
    path: {
        saksnummer: string;
    };
    query?: never;
    url: '/api/sak/{saksnummer}';
};

export type GetSakBySaksnummerErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetail;
};

export type GetSakBySaksnummerError = GetSakBySaksnummerErrors[keyof GetSakBySaksnummerErrors];

export type GetSakBySaksnummerResponses = {
    /**
     * OK
     */
    200: SakDto;
};

export type GetSakBySaksnummerResponse = GetSakBySaksnummerResponses[keyof GetSakBySaksnummerResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};