CREATE TABLE brev
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid           UUID                                    NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sak_id         BIGINT                                  NOT NULL,
    tittel         TEXT,
    innhold        TEXT,
    type           VARCHAR(50)                             NOT NULL,
    mottaker_type  VARCHAR(50)                            NOT NULL,
    status         VARCHAR(50)                            NOT NULL,
    journalpost_id VARCHAR(50),
    CONSTRAINT pk_brev PRIMARY KEY (id)
);

CREATE TABLE endringslogg
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id      BIGINT                                  NOT NULL,
    tidspunkt   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    endret_av   VARCHAR(50)                            NOT NULL,
    type        VARCHAR(50)                            NOT NULL,
    endring     TEXT                            NOT NULL,
    beskrivelse TEXT,
    CONSTRAINT pk_endringslogg PRIMARY KEY (id)
);

CREATE TABLE forhandtilsagn
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID                                    NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    belop        INTEGER                                 NOT NULL,
    CONSTRAINT pk_forhandtilsagn PRIMARY KEY (id)
);

CREATE TABLE sak
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type                    VARCHAR(255)                            NOT NULL,
    behandlings_teller      INTEGER                                 NOT NULL,
    fnr                     VARCHAR(11)                             NOT NULL,
    beskrivelse             TEXT,
    status                  VARCHAR(50)                            NOT NULL,
    vedtaks_resultat        VARCHAR(50),
    begrunnelse             TEXT,
    opprettet               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    soknads_dato            date,
    tildelings_aar          INTEGER,
    utbetaling_id           BIGINT,
    forhandstilsagn_id      BIGINT,
    saksbehandler_nav_ident VARCHAR(50)                            NOT NULL,
    saksbehandler_navn      TEXT                            NOT NULL,
    attestant_nav_ident     VARCHAR(50),
    attestant_navn          TEXT,
    CONSTRAINT pk_sak PRIMARY KEY (id)
);

CREATE TABLE utbetaling
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                 UUID                                    NOT NULL,
    belop                INTEGER                                 NOT NULL,
    utbetaling_tidspunkt TIMESTAMP WITHOUT TIME ZONE,
    utbetaling_status    VARCHAR(50)                            NOT NULL,
    CONSTRAINT pk_utbetaling PRIMARY KEY (id)
);

CREATE TABLE vedtak
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id                  BIGINT                                  NOT NULL,
    behandlingsnummer       VARCHAR(50)                            NOT NULL,
    type                    VARCHAR(50)                            NOT NULL,
    fnr                     VARCHAR(11)                            NOT NULL,
    beskrivelse             TEXT                            NOT NULL,
    resultat                VARCHAR(50)                            NOT NULL,
    begrunnelse             TEXT,
    utbetalings_type        VARCHAR(50)                            NOT NULL,
    belop                   INTEGER,
    soknads_dato            date                                    NOT NULL,
    tildelings_aar          INTEGER,
    vedtaks_tidspunkt       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    saksbehandler_nav_ident VARCHAR(50)                            NOT NULL,
    saksbehandler_navn      TEXT                            NOT NULL,
    attestant_nav_ident     VARCHAR(50)                            NOT NULL,
    attestant_navn          TEXT                            NOT NULL,
    CONSTRAINT pk_vedtak PRIMARY KEY (id)
);

ALTER TABLE brev
    ADD CONSTRAINT uc_brev_uuid UNIQUE (uuid);

ALTER TABLE forhandtilsagn
    ADD CONSTRAINT uc_forhandtilsagn_uuid UNIQUE (uuid);

ALTER TABLE utbetaling
    ADD CONSTRAINT uc_utbetaling_uuid UNIQUE (uuid);

ALTER TABLE vedtak
    ADD CONSTRAINT uc_vedtak_behandlingsnummer UNIQUE (behandlingsnummer);

ALTER TABLE brev
    ADD CONSTRAINT FK_BREV_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (id);

ALTER TABLE endringslogg
    ADD CONSTRAINT FK_ENDRINGSLOGG_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (id);

ALTER TABLE sak
    ADD CONSTRAINT FK_SAK_ON_FORHANDSTILSAGN FOREIGN KEY (forhandstilsagn_id) REFERENCES forhandtilsagn (id);

ALTER TABLE sak
    ADD CONSTRAINT FK_SAK_ON_UTBETALING FOREIGN KEY (utbetaling_id) REFERENCES utbetaling (id);

ALTER TABLE vedtak
    ADD CONSTRAINT FK_VEDTAK_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (id);

-- Indekser for optimalisering av spørringer
CREATE INDEX idx_brev_sak_id ON brev(sak_id);
CREATE INDEX idx_brev_uuid ON brev(uuid);

CREATE INDEX idx_endringslogg_sak_id ON endringslogg(sak_id);

CREATE INDEX idx_vedtak_sak_id ON vedtak(sak_id);
CREATE INDEX idx_vedtak_behandlingsnummer ON vedtak(behandlingsnummer);

CREATE INDEX idx_utbetaling_uuid ON utbetaling(uuid);
CREATE INDEX idx_utbetaling_status ON utbetaling(utbetaling_status);

CREATE INDEX idx_forhandtilsagn_uuid ON forhandtilsagn(uuid);

CREATE INDEX idx_sak_fnr ON sak(fnr);
CREATE INDEX idx_sak_status ON sak(status);
