-- =====================================================
-- TABELL: oppgave
-- =====================================================
CREATE TABLE oppgave
(
    oppgave_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id              BIGINT                                  NOT NULL,
    ekstern_oppgave_id  BIGINT                                  NOT NULL,
    type                VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_oppgave PRIMARY KEY (oppgave_id)
);

ALTER TABLE oppgave
    ADD CONSTRAINT FK_OPPGAVE_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (sak_id);

CREATE INDEX idx_oppgave_sak_id ON oppgave (sak_id);
CREATE INDEX idx_oppgave_ekstern_oppgave_id ON oppgave (ekstern_oppgave_id);
