-- =====================================================
-- TABELL: utbetaling
-- =====================================================
CREATE TABLE utbetaling
(
    utbetaling_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    utbetaling_uuid      UUID                                    NOT NULL,
    belop                INTEGER                                 NOT NULL,
    utbetaling_tidspunkt TIMESTAMP WITH TIME ZONE,
    utbetaling_status    VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_utbetaling PRIMARY KEY (utbetaling_id)
);

ALTER TABLE utbetaling
    ADD CONSTRAINT uc_utbetaling_uuid UNIQUE (utbetaling_uuid);

CREATE INDEX idx_utbetaling_uuid ON utbetaling (utbetaling_uuid);
CREATE INDEX idx_utbetaling_status ON utbetaling (utbetaling_status);

-- =====================================================
-- TABELL: forhandtilsagn
-- =====================================================
CREATE TABLE forhandtilsagn
(
    forhandtilsagn_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    forhandtilsagn_uuid UUID                                    NOT NULL,
    created_date        TIMESTAMP WITH TIME ZONE                NOT NULL,
    belop               INTEGER                                 NOT NULL,
    CONSTRAINT pk_forhandtilsagn PRIMARY KEY (forhandtilsagn_id)
);

ALTER TABLE forhandtilsagn
    ADD CONSTRAINT uc_forhandtilsagn_uuid UNIQUE (forhandtilsagn_uuid);

CREATE INDEX idx_forhandtilsagn_uuid ON forhandtilsagn (forhandtilsagn_uuid);


-- =====================================================
-- TABELL: sak
-- =====================================================
CREATE TABLE sak
(
    sak_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stonads_type            VARCHAR(255)                            NOT NULL,
    behandlings_teller      INTEGER                                 NOT NULL,
    fnr                     VARCHAR(11)                             NOT NULL,
    beskrivelse             TEXT,
    sak_status              VARCHAR(50)                             NOT NULL,
    vedtaks_resultat        VARCHAR(50),
    begrunnelse             TEXT,
    opprettet               TIMESTAMP WITH TIME ZONE                NOT NULL,
    soknads_dato            date,
    tildelings_aar          INTEGER,
    utbetaling_id           BIGINT,
    forhandtilsagn_id       BIGINT,
    saksbehandler_nav_ident VARCHAR(50)                             NOT NULL,
    saksbehandler_navn      TEXT                                    NOT NULL,
    attestant_nav_ident     VARCHAR(50),
    attestant_navn          TEXT,
    CONSTRAINT pk_sak PRIMARY KEY (sak_id)
);

CREATE INDEX idx_sak_fnr ON sak (fnr);
CREATE INDEX idx_sak_status ON sak (sak_status);

ALTER TABLE sak
    ADD CONSTRAINT FK_SAK_ON_UTBETALING FOREIGN KEY (utbetaling_id) REFERENCES utbetaling (utbetaling_id);
ALTER TABLE sak
    ADD CONSTRAINT FK_SAK_ON_FORHANDSTILSAGN FOREIGN KEY (forhandtilsagn_id) REFERENCES forhandtilsagn (forhandtilsagn_id);



-- =====================================================
-- TABELL: brev
-- =====================================================
CREATE TABLE brev
(
    brev_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brev_uuid          UUID                                    NOT NULL,
    created_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    sak_id             BIGINT                                  NOT NULL,
    tittel             TEXT,
    innhold            TEXT,
    brev_type          VARCHAR(50)                             NOT NULL,
    brev_mottaker_type VARCHAR(50)                             NOT NULL,
    brev_status        VARCHAR(50)                             NOT NULL,
    journalpost_id     VARCHAR(50),
    CONSTRAINT pk_brev PRIMARY KEY (brev_id)
);

ALTER TABLE brev
    ADD CONSTRAINT uc_brev_uuid UNIQUE (brev_uuid);

ALTER TABLE brev
    ADD CONSTRAINT FK_BREV_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (sak_id);

CREATE INDEX idx_brev_sak_id ON brev (sak_id);
CREATE INDEX idx_brev_uuid ON brev (brev_uuid);

-- =====================================================
-- TABELL: endringslogg
-- =====================================================
CREATE TABLE endringslogg
(
    endringslogg_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id            BIGINT                                  NOT NULL,
    tidspunkt         TIMESTAMP WITH TIME ZONE                NOT NULL,
    endret_av         VARCHAR(50)                             NOT NULL,
    endringslogg_type VARCHAR(50)                             NOT NULL,
    endring           TEXT                                    NOT NULL,
    beskrivelse       TEXT,
    CONSTRAINT pk_endringslogg PRIMARY KEY (endringslogg_id)
);

ALTER TABLE endringslogg
    ADD CONSTRAINT FK_ENDRINGSLOGG_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (sak_id);

CREATE INDEX idx_endringslogg_sak_id ON endringslogg (sak_id);

-- =====================================================
-- TABELL: vedtak
-- =====================================================
CREATE TABLE vedtak
(
    vedtak_id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id                  BIGINT                                  NOT NULL,
    behandlings_teller      INTEGER                                 NOT NULL,
    stonads_type            VARCHAR(50)                             NOT NULL,
    fnr                     VARCHAR(11)                             NOT NULL,
    beskrivelse             TEXT                                    NOT NULL,
    vedtaks_resultat        VARCHAR(50)                             NOT NULL,
    begrunnelse             TEXT,
    utbetalings_type        VARCHAR(50)                             NOT NULL,
    belop                   INTEGER,
    soknads_dato            date                                    NOT NULL,
    tildelings_aar          INTEGER,
    vedtaks_tidspunkt       TIMESTAMP WITH TIME ZONE                NOT NULL,
    saksbehandler_nav_ident VARCHAR(50)                             NOT NULL,
    saksbehandler_navn      TEXT                                    NOT NULL,
    attestant_nav_ident     VARCHAR(50)                             NOT NULL,
    attestant_navn          TEXT                                    NOT NULL,
    CONSTRAINT pk_vedtak PRIMARY KEY (vedtak_id)
);

ALTER TABLE vedtak
    ADD CONSTRAINT uc_vedtak_behandlingsnummer UNIQUE (behandlings_teller, sak_id);

ALTER TABLE vedtak
    ADD CONSTRAINT FK_VEDTAK_ON_SAK FOREIGN KEY (sak_id) REFERENCES sak (sak_id);

CREATE INDEX idx_vedtak_sak_id ON vedtak (sak_id);

