-- =====================================================
-- TABELL: oppgave
-- =====================================================
CREATE TABLE oppgave
(
    oppgave_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sak_id              BIGINT references sak(sak_id)           NOT NULL,
    ekstern_oppgave_id  BIGINT UNIQUE                           NOT NULL,
    type                VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_oppgave PRIMARY KEY (oppgave_id)
);

CREATE INDEX idx_oppgave_sak_id ON oppgave (sak_id);
