package no.nav.historisk.superhelt.endringslogg

enum class EndringsloggType {
    DOKUMENT_MOTTATT,
    OPPRETTET_SAK,
    OPPDATERTE_SAKSDETALJER,
    TIL_ATTESTERING,
    ATTESTERT_SAK,
    FERDIGSTILT_SAK,
    ATTESTERING_UNDERKJENT,
    GJENAPNET_SAK,
    SENDT_BREV,
    UTBETALING_OK,
    UTBETALING_FEILET,
}
