package no.nav.historisk.superhelt.endringslogg

enum class EndringsloggType {
    DOKUMENT_MOTTATT,
    OPPRETTET_SAK,
    TIL_ATTESTERING,
    ATTESTERT_SAK,
    FERDIGSTILT_SAK,
    ATTESTERING_UNDERKJENT,
    GJENAPNET_SAK,
    SENDT_BREV,
    UTBETALING_OK,
    UTBETALING_FEILET,
    FEILREGISTERT,
    HENLAGT_SAK,
    TILBAKESTILT_SAK,
    DOKUMENT_JOURNALFOERT_EKSISTERENDE_SAK,
    KLAGE_SENDT_KABAL,

    // Kabal-events mottatt via Kafka
    KABAL_KLAGEBEHANDLING_AVSLUTTET,
    KABAL_ANKEBEHANDLING_OPPRETTET,
    KABAL_ANKEBEHANDLING_AVSLUTTET,
    KABAL_ANKE_I_TRYGDERETTEN_OPPRETTET,
    KABAL_BEHANDLING_ETTER_TRYGDERETTEN_OPPHEVET_AVSLUTTET,
    KABAL_OMGJOERINGSKRAVBEHANDLING_AVSLUTTET,
    KABAL_GJENOPPTAKSBEHANDLING_AVSLUTTET,
    KABAL_BEHANDLING_FEILREGISTRERT,
}
