package no.nav.helved

/**
 * Klassekoder for helved utbetalinger.
 *
 * https://github.com/navikt/helved-utbetaling/blob/main/models/main/models/Utbetalinger.kt#L425
 */

enum class KlasseKode(internal val klassekode: String) {
    @Deprecated("Brukes ikke lenger i helved")
    TILSKUDD_SMÅHJELPEMIDLER("HJRIM"),// HJRIM

    /* HelseTjensester */
    REISEUTGIFTER("HTRUTR"),
    ORTOPEDISK_PROTESE("HTOHPR"),
    ORTOSE("HTOHHÅ"),
    SPESIALSKO("HTOHSKBA"),
    PARYKK("HTOHPAAV"),
    ANSIKTSDEFEKTPROTESE("HTOHAD"),
    BRYSTPROTESE("HTOHBP"),
    ØYEPROTESE("HTOHØP"),
    VANLIGE_SKO("HTOHAS"),
    FOTSENG("HTOHFTEN"),

    /* Hjelpemidler*/
    HØREAPPARAT_ANSKAFFELSE("H-APP"),
    HØREAPPARAT_REPARASJON("H-APPREP"),
    HØREAPPARAT_EGENBETALING("H-APPEGENBET"),
    LEGEERKLÆRING_SPESIALIST("LEGEERKLSPES"),
    LEGEERKLÆRING_ALLMENN("LEGEERKLALM"),
    ARBEIDSPLASSVURDERING_FYSIOTERAPEUT("ARBPLVURD"),
    OPPLÆRING_TILPASNING_KURS_SYN("OPPLTILP-SYN"),
    OPPLÆRING_TILPASNING_KURS_HØRSEL("OPPLTILP-HORSEL"),
    OPPLÆRING_TILPASNING_KURS_DØVBLIND("OPPLTILP-DOVBLIND"),
    OPPLÆRING_TILPASNING_FOLKEHØGSKOLE("OPPLTILP-FHSKOLE"),
    OPPLÆRING_TILPASNING_BRISKEBY("OPPLTILP-BRISKEBY"),
    TINNITUSMASKERER("HJTINNITUS"),
    HJELPEMIDLER_SELVSTENDIG_NÆRINGSDRIVENDE("HJARBLIVSELVST"),
    HJELPEMIDLER_ARBEID_UTDANNING("HJARBUTD"),
    HJELPEMIDLER_ATTFØRING("HJATTF"),
    HJELPEMIDLER_GRUNNMØNSTER("HJGRUNNM"),
    HJELPEMIDLER_ANNET("HJANNET"),
    SEKSUALTEKNISKE_HJELPEMIDLER("HJSEXTEKN"),
    REISE_OPPHOLD("REOPPH"),
    REISE_OPPHOLD_BIL("REOPPH-BIL"),
    REISE_OPPHOLD_HJELPEMIDLER("REOPPH-HJ"),
    REISE_OPPHOLD_ORTOPEDISKE_HJELPEMIDLER("REOPPH-ORT"),
    TAPT_ARBEIDSFORTJENESTE_LEDSAGER("TAPTARBLEDS"),
    TAPT_ARBEIDSFORTJENESTE_LEDSAGER_IOP("TAPTARBLEDS-IOP"),
    REPARASJON_HJELPEMIDLER_UTLAND("HJREP"),
    SYNSHJELPEMIDLER("HJSYN"),
    BOLIGTILSKUDD("HJBOL"),
    FØRERHUND_VETERINÆR("HJHUND"),
    ØREPROPPER("HJPROPP"),
    BILTILSKUDD_GRUPPE_1("HJBILGR1"),
    KJØREOPPLÆRING_GRUPPE_1("HJBILOPPLGR1"),
    KJØREOPPLÆRING_GRUPPE_2("HJBILOPPLGR2"),
    BILTILSKUDD_GRUPPE_2("HJBILGR2"),
    DATAUTSTYR("HJDATA"),
    SERVICEHUND_REISEUTGIFTER("SEHUNDREIS"),
    SERVICEHUND_VETERINÆR("SEHUNDVET"),
    APP_KOGNISJON("HJAPPKOG"),
    APP_KOMMUNIKASJON("HJAPPKOM"),
    APP_LESE_OG_SKRIVESTØTTE("HJAPPLES"),
    APP_SYN("HJAPPSYN"),
    BEHANDLINGSBRILLE_SATS_1("HTBDBR"),
    BEHANDLINGSBRILLE_SATS_2("HTBDBI"),
    BEHANDLINGSBRILLE_INDIVIDUELL("HTBDIB"),
    KONTAKTLINSER_BEHANDLING("HTBDKB"),
    REPARASJON_BEHANDLINGSBRILLE("HTBDRB"),
}
