/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SakSaksnummerRouteRouteImport } from './routes/sak/$saksnummer/route'
import { Route as OppgaveOppgaveidRouteRouteImport } from './routes/oppgave/$oppgaveid/route'
import { Route as SakSaksnummerIndexRouteImport } from './routes/sak/$saksnummer/index'
import { Route as PersonPersonidIndexRouteImport } from './routes/person/$personid/index'
import { Route as OppgaveOppgaveidIndexRouteImport } from './routes/oppgave/$oppgaveid/index'
import { Route as SakSaksnummerVedtaksbrevbrukerRouteImport } from './routes/sak/$saksnummer/vedtaksbrevbruker'
import { Route as SakSaksnummerOppsummeringRouteImport } from './routes/sak/$saksnummer/oppsummering'
import { Route as SakSaksnummerOpplysningerRouteImport } from './routes/sak/$saksnummer/opplysninger'
import { Route as SakSaksnummerHenleggRouteImport } from './routes/sak/$saksnummer/henlegg'
import { Route as SakSaksnummerFritekstbrevRouteImport } from './routes/sak/$saksnummer/fritekstbrev'
import { Route as SakSaksnummerFeilregistrerRouteImport } from './routes/sak/$saksnummer/feilregistrer'
import { Route as OppgaveOppgaveidJournalforRouteImport } from './routes/oppgave/$oppgaveid/journalfor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SakSaksnummerRouteRoute = SakSaksnummerRouteRouteImport.update({
  id: '/sak/$saksnummer',
  path: '/sak/$saksnummer',
  getParentRoute: () => rootRouteImport,
} as any)
const OppgaveOppgaveidRouteRoute = OppgaveOppgaveidRouteRouteImport.update({
  id: '/oppgave/$oppgaveid',
  path: '/oppgave/$oppgaveid',
  getParentRoute: () => rootRouteImport,
} as any)
const SakSaksnummerIndexRoute = SakSaksnummerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SakSaksnummerRouteRoute,
} as any)
const PersonPersonidIndexRoute = PersonPersonidIndexRouteImport.update({
  id: '/person/$personid/',
  path: '/person/$personid/',
  getParentRoute: () => rootRouteImport,
} as any)
const OppgaveOppgaveidIndexRoute = OppgaveOppgaveidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OppgaveOppgaveidRouteRoute,
} as any)
const SakSaksnummerVedtaksbrevbrukerRoute =
  SakSaksnummerVedtaksbrevbrukerRouteImport.update({
    id: '/vedtaksbrevbruker',
    path: '/vedtaksbrevbruker',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const SakSaksnummerOppsummeringRoute =
  SakSaksnummerOppsummeringRouteImport.update({
    id: '/oppsummering',
    path: '/oppsummering',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const SakSaksnummerOpplysningerRoute =
  SakSaksnummerOpplysningerRouteImport.update({
    id: '/opplysninger',
    path: '/opplysninger',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const SakSaksnummerHenleggRoute = SakSaksnummerHenleggRouteImport.update({
  id: '/henlegg',
  path: '/henlegg',
  getParentRoute: () => SakSaksnummerRouteRoute,
} as any)
const SakSaksnummerFritekstbrevRoute =
  SakSaksnummerFritekstbrevRouteImport.update({
    id: '/fritekstbrev',
    path: '/fritekstbrev',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const SakSaksnummerFeilregistrerRoute =
  SakSaksnummerFeilregistrerRouteImport.update({
    id: '/feilregistrer',
    path: '/feilregistrer',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const OppgaveOppgaveidJournalforRoute =
  OppgaveOppgaveidJournalforRouteImport.update({
    id: '/journalfor',
    path: '/journalfor',
    getParentRoute: () => OppgaveOppgaveidRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oppgave/$oppgaveid': typeof OppgaveOppgaveidRouteRouteWithChildren
  '/sak/$saksnummer': typeof SakSaksnummerRouteRouteWithChildren
  '/oppgave/$oppgaveid/journalfor': typeof OppgaveOppgaveidJournalforRoute
  '/sak/$saksnummer/feilregistrer': typeof SakSaksnummerFeilregistrerRoute
  '/sak/$saksnummer/fritekstbrev': typeof SakSaksnummerFritekstbrevRoute
  '/sak/$saksnummer/henlegg': typeof SakSaksnummerHenleggRoute
  '/sak/$saksnummer/opplysninger': typeof SakSaksnummerOpplysningerRoute
  '/sak/$saksnummer/oppsummering': typeof SakSaksnummerOppsummeringRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/oppgave/$oppgaveid/': typeof OppgaveOppgaveidIndexRoute
  '/person/$personid/': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer/': typeof SakSaksnummerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oppgave/$oppgaveid/journalfor': typeof OppgaveOppgaveidJournalforRoute
  '/sak/$saksnummer/feilregistrer': typeof SakSaksnummerFeilregistrerRoute
  '/sak/$saksnummer/fritekstbrev': typeof SakSaksnummerFritekstbrevRoute
  '/sak/$saksnummer/henlegg': typeof SakSaksnummerHenleggRoute
  '/sak/$saksnummer/opplysninger': typeof SakSaksnummerOpplysningerRoute
  '/sak/$saksnummer/oppsummering': typeof SakSaksnummerOppsummeringRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/oppgave/$oppgaveid': typeof OppgaveOppgaveidIndexRoute
  '/person/$personid': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer': typeof SakSaksnummerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oppgave/$oppgaveid': typeof OppgaveOppgaveidRouteRouteWithChildren
  '/sak/$saksnummer': typeof SakSaksnummerRouteRouteWithChildren
  '/oppgave/$oppgaveid/journalfor': typeof OppgaveOppgaveidJournalforRoute
  '/sak/$saksnummer/feilregistrer': typeof SakSaksnummerFeilregistrerRoute
  '/sak/$saksnummer/fritekstbrev': typeof SakSaksnummerFritekstbrevRoute
  '/sak/$saksnummer/henlegg': typeof SakSaksnummerHenleggRoute
  '/sak/$saksnummer/opplysninger': typeof SakSaksnummerOpplysningerRoute
  '/sak/$saksnummer/oppsummering': typeof SakSaksnummerOppsummeringRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/oppgave/$oppgaveid/': typeof OppgaveOppgaveidIndexRoute
  '/person/$personid/': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer/': typeof SakSaksnummerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oppgave/$oppgaveid'
    | '/sak/$saksnummer'
    | '/oppgave/$oppgaveid/journalfor'
    | '/sak/$saksnummer/feilregistrer'
    | '/sak/$saksnummer/fritekstbrev'
    | '/sak/$saksnummer/henlegg'
    | '/sak/$saksnummer/opplysninger'
    | '/sak/$saksnummer/oppsummering'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/oppgave/$oppgaveid/'
    | '/person/$personid/'
    | '/sak/$saksnummer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oppgave/$oppgaveid/journalfor'
    | '/sak/$saksnummer/feilregistrer'
    | '/sak/$saksnummer/fritekstbrev'
    | '/sak/$saksnummer/henlegg'
    | '/sak/$saksnummer/opplysninger'
    | '/sak/$saksnummer/oppsummering'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/oppgave/$oppgaveid'
    | '/person/$personid'
    | '/sak/$saksnummer'
  id:
    | '__root__'
    | '/'
    | '/oppgave/$oppgaveid'
    | '/sak/$saksnummer'
    | '/oppgave/$oppgaveid/journalfor'
    | '/sak/$saksnummer/feilregistrer'
    | '/sak/$saksnummer/fritekstbrev'
    | '/sak/$saksnummer/henlegg'
    | '/sak/$saksnummer/opplysninger'
    | '/sak/$saksnummer/oppsummering'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/oppgave/$oppgaveid/'
    | '/person/$personid/'
    | '/sak/$saksnummer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OppgaveOppgaveidRouteRoute: typeof OppgaveOppgaveidRouteRouteWithChildren
  SakSaksnummerRouteRoute: typeof SakSaksnummerRouteRouteWithChildren
  PersonPersonidIndexRoute: typeof PersonPersonidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sak/$saksnummer': {
      id: '/sak/$saksnummer'
      path: '/sak/$saksnummer'
      fullPath: '/sak/$saksnummer'
      preLoaderRoute: typeof SakSaksnummerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppgave/$oppgaveid': {
      id: '/oppgave/$oppgaveid'
      path: '/oppgave/$oppgaveid'
      fullPath: '/oppgave/$oppgaveid'
      preLoaderRoute: typeof OppgaveOppgaveidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sak/$saksnummer/': {
      id: '/sak/$saksnummer/'
      path: '/'
      fullPath: '/sak/$saksnummer/'
      preLoaderRoute: typeof SakSaksnummerIndexRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/person/$personid/': {
      id: '/person/$personid/'
      path: '/person/$personid'
      fullPath: '/person/$personid/'
      preLoaderRoute: typeof PersonPersonidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppgave/$oppgaveid/': {
      id: '/oppgave/$oppgaveid/'
      path: '/'
      fullPath: '/oppgave/$oppgaveid/'
      preLoaderRoute: typeof OppgaveOppgaveidIndexRouteImport
      parentRoute: typeof OppgaveOppgaveidRouteRoute
    }
    '/sak/$saksnummer/vedtaksbrevbruker': {
      id: '/sak/$saksnummer/vedtaksbrevbruker'
      path: '/vedtaksbrevbruker'
      fullPath: '/sak/$saksnummer/vedtaksbrevbruker'
      preLoaderRoute: typeof SakSaksnummerVedtaksbrevbrukerRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/oppsummering': {
      id: '/sak/$saksnummer/oppsummering'
      path: '/oppsummering'
      fullPath: '/sak/$saksnummer/oppsummering'
      preLoaderRoute: typeof SakSaksnummerOppsummeringRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/opplysninger': {
      id: '/sak/$saksnummer/opplysninger'
      path: '/opplysninger'
      fullPath: '/sak/$saksnummer/opplysninger'
      preLoaderRoute: typeof SakSaksnummerOpplysningerRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/henlegg': {
      id: '/sak/$saksnummer/henlegg'
      path: '/henlegg'
      fullPath: '/sak/$saksnummer/henlegg'
      preLoaderRoute: typeof SakSaksnummerHenleggRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/fritekstbrev': {
      id: '/sak/$saksnummer/fritekstbrev'
      path: '/fritekstbrev'
      fullPath: '/sak/$saksnummer/fritekstbrev'
      preLoaderRoute: typeof SakSaksnummerFritekstbrevRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/feilregistrer': {
      id: '/sak/$saksnummer/feilregistrer'
      path: '/feilregistrer'
      fullPath: '/sak/$saksnummer/feilregistrer'
      preLoaderRoute: typeof SakSaksnummerFeilregistrerRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/oppgave/$oppgaveid/journalfor': {
      id: '/oppgave/$oppgaveid/journalfor'
      path: '/journalfor'
      fullPath: '/oppgave/$oppgaveid/journalfor'
      preLoaderRoute: typeof OppgaveOppgaveidJournalforRouteImport
      parentRoute: typeof OppgaveOppgaveidRouteRoute
    }
  }
}

interface OppgaveOppgaveidRouteRouteChildren {
  OppgaveOppgaveidJournalforRoute: typeof OppgaveOppgaveidJournalforRoute
  OppgaveOppgaveidIndexRoute: typeof OppgaveOppgaveidIndexRoute
}

const OppgaveOppgaveidRouteRouteChildren: OppgaveOppgaveidRouteRouteChildren = {
  OppgaveOppgaveidJournalforRoute: OppgaveOppgaveidJournalforRoute,
  OppgaveOppgaveidIndexRoute: OppgaveOppgaveidIndexRoute,
}

const OppgaveOppgaveidRouteRouteWithChildren =
  OppgaveOppgaveidRouteRoute._addFileChildren(
    OppgaveOppgaveidRouteRouteChildren,
  )

interface SakSaksnummerRouteRouteChildren {
  SakSaksnummerFeilregistrerRoute: typeof SakSaksnummerFeilregistrerRoute
  SakSaksnummerFritekstbrevRoute: typeof SakSaksnummerFritekstbrevRoute
  SakSaksnummerHenleggRoute: typeof SakSaksnummerHenleggRoute
  SakSaksnummerOpplysningerRoute: typeof SakSaksnummerOpplysningerRoute
  SakSaksnummerOppsummeringRoute: typeof SakSaksnummerOppsummeringRoute
  SakSaksnummerVedtaksbrevbrukerRoute: typeof SakSaksnummerVedtaksbrevbrukerRoute
  SakSaksnummerIndexRoute: typeof SakSaksnummerIndexRoute
}

const SakSaksnummerRouteRouteChildren: SakSaksnummerRouteRouteChildren = {
  SakSaksnummerFeilregistrerRoute: SakSaksnummerFeilregistrerRoute,
  SakSaksnummerFritekstbrevRoute: SakSaksnummerFritekstbrevRoute,
  SakSaksnummerHenleggRoute: SakSaksnummerHenleggRoute,
  SakSaksnummerOpplysningerRoute: SakSaksnummerOpplysningerRoute,
  SakSaksnummerOppsummeringRoute: SakSaksnummerOppsummeringRoute,
  SakSaksnummerVedtaksbrevbrukerRoute: SakSaksnummerVedtaksbrevbrukerRoute,
  SakSaksnummerIndexRoute: SakSaksnummerIndexRoute,
}

const SakSaksnummerRouteRouteWithChildren =
  SakSaksnummerRouteRoute._addFileChildren(SakSaksnummerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OppgaveOppgaveidRouteRoute: OppgaveOppgaveidRouteRouteWithChildren,
  SakSaksnummerRouteRoute: SakSaksnummerRouteRouteWithChildren,
  PersonPersonidIndexRoute: PersonPersonidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
