/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SakSaksnummerRouteRouteImport } from './routes/sak/$saksnummer/route'
import { Route as SakSaksnummerIndexRouteImport } from './routes/sak/$saksnummer/index'
import { Route as PersonPersonidIndexRouteImport } from './routes/person/$personid/index'
import { Route as SakSaksnummerVedtaksbrevbrukerRouteImport } from './routes/sak/$saksnummer/vedtaksbrevbruker'
import { Route as SakSaksnummerVedtakRouteImport } from './routes/sak/$saksnummer/vedtak'
import { Route as SakSaksnummerSoknadRouteImport } from './routes/sak/$saksnummer/soknad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SakSaksnummerRouteRoute = SakSaksnummerRouteRouteImport.update({
  id: '/sak/$saksnummer',
  path: '/sak/$saksnummer',
  getParentRoute: () => rootRouteImport,
} as any)
const SakSaksnummerIndexRoute = SakSaksnummerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SakSaksnummerRouteRoute,
} as any)
const PersonPersonidIndexRoute = PersonPersonidIndexRouteImport.update({
  id: '/person/$personid/',
  path: '/person/$personid/',
  getParentRoute: () => rootRouteImport,
} as any)
const SakSaksnummerVedtaksbrevbrukerRoute =
  SakSaksnummerVedtaksbrevbrukerRouteImport.update({
    id: '/vedtaksbrevbruker',
    path: '/vedtaksbrevbruker',
    getParentRoute: () => SakSaksnummerRouteRoute,
  } as any)
const SakSaksnummerVedtakRoute = SakSaksnummerVedtakRouteImport.update({
  id: '/vedtak',
  path: '/vedtak',
  getParentRoute: () => SakSaksnummerRouteRoute,
} as any)
const SakSaksnummerSoknadRoute = SakSaksnummerSoknadRouteImport.update({
  id: '/soknad',
  path: '/soknad',
  getParentRoute: () => SakSaksnummerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sak/$saksnummer': typeof SakSaksnummerRouteRouteWithChildren
  '/sak/$saksnummer/soknad': typeof SakSaksnummerSoknadRoute
  '/sak/$saksnummer/vedtak': typeof SakSaksnummerVedtakRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/person/$personid': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer/': typeof SakSaksnummerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sak/$saksnummer/soknad': typeof SakSaksnummerSoknadRoute
  '/sak/$saksnummer/vedtak': typeof SakSaksnummerVedtakRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/person/$personid': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer': typeof SakSaksnummerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sak/$saksnummer': typeof SakSaksnummerRouteRouteWithChildren
  '/sak/$saksnummer/soknad': typeof SakSaksnummerSoknadRoute
  '/sak/$saksnummer/vedtak': typeof SakSaksnummerVedtakRoute
  '/sak/$saksnummer/vedtaksbrevbruker': typeof SakSaksnummerVedtaksbrevbrukerRoute
  '/person/$personid/': typeof PersonPersonidIndexRoute
  '/sak/$saksnummer/': typeof SakSaksnummerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sak/$saksnummer'
    | '/sak/$saksnummer/soknad'
    | '/sak/$saksnummer/vedtak'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/person/$personid'
    | '/sak/$saksnummer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sak/$saksnummer/soknad'
    | '/sak/$saksnummer/vedtak'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/person/$personid'
    | '/sak/$saksnummer'
  id:
    | '__root__'
    | '/'
    | '/sak/$saksnummer'
    | '/sak/$saksnummer/soknad'
    | '/sak/$saksnummer/vedtak'
    | '/sak/$saksnummer/vedtaksbrevbruker'
    | '/person/$personid/'
    | '/sak/$saksnummer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SakSaksnummerRouteRoute: typeof SakSaksnummerRouteRouteWithChildren
  PersonPersonidIndexRoute: typeof PersonPersonidIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sak/$saksnummer': {
      id: '/sak/$saksnummer'
      path: '/sak/$saksnummer'
      fullPath: '/sak/$saksnummer'
      preLoaderRoute: typeof SakSaksnummerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sak/$saksnummer/': {
      id: '/sak/$saksnummer/'
      path: '/'
      fullPath: '/sak/$saksnummer/'
      preLoaderRoute: typeof SakSaksnummerIndexRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/person/$personid/': {
      id: '/person/$personid/'
      path: '/person/$personid'
      fullPath: '/person/$personid'
      preLoaderRoute: typeof PersonPersonidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sak/$saksnummer/vedtaksbrevbruker': {
      id: '/sak/$saksnummer/vedtaksbrevbruker'
      path: '/vedtaksbrevbruker'
      fullPath: '/sak/$saksnummer/vedtaksbrevbruker'
      preLoaderRoute: typeof SakSaksnummerVedtaksbrevbrukerRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/vedtak': {
      id: '/sak/$saksnummer/vedtak'
      path: '/vedtak'
      fullPath: '/sak/$saksnummer/vedtak'
      preLoaderRoute: typeof SakSaksnummerVedtakRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
    '/sak/$saksnummer/soknad': {
      id: '/sak/$saksnummer/soknad'
      path: '/soknad'
      fullPath: '/sak/$saksnummer/soknad'
      preLoaderRoute: typeof SakSaksnummerSoknadRouteImport
      parentRoute: typeof SakSaksnummerRouteRoute
    }
  }
}

interface SakSaksnummerRouteRouteChildren {
  SakSaksnummerSoknadRoute: typeof SakSaksnummerSoknadRoute
  SakSaksnummerVedtakRoute: typeof SakSaksnummerVedtakRoute
  SakSaksnummerVedtaksbrevbrukerRoute: typeof SakSaksnummerVedtaksbrevbrukerRoute
  SakSaksnummerIndexRoute: typeof SakSaksnummerIndexRoute
}

const SakSaksnummerRouteRouteChildren: SakSaksnummerRouteRouteChildren = {
  SakSaksnummerSoknadRoute: SakSaksnummerSoknadRoute,
  SakSaksnummerVedtakRoute: SakSaksnummerVedtakRoute,
  SakSaksnummerVedtaksbrevbrukerRoute: SakSaksnummerVedtaksbrevbrukerRoute,
  SakSaksnummerIndexRoute: SakSaksnummerIndexRoute,
}

const SakSaksnummerRouteRouteWithChildren =
  SakSaksnummerRouteRoute._addFileChildren(SakSaksnummerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SakSaksnummerRouteRoute: SakSaksnummerRouteRouteWithChildren,
  PersonPersonidIndexRoute: PersonPersonidIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
