AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:8102/azure-mock
AZURE_APP_CLIENT_ID: "historisk-superapp"
KAFKA_BROKERS: localhost:9092

DB_USERNAME: postgres
DB_PASSWORD: test
DB_JDBC_URL: jdbc:postgresql://localhost:5032/historisk-superhelt

NAIS_APP_IMAGE: latest
NAIS_CLUSTER_NAME: dev
APP_ENV: dev

# overser audience sjekken i dev miljo pga problemer med mock-oidc og aud i jwt token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: ""
#  web:
#    resources:
#      static-locations: file:./frontend/dist
  kafka:
    security:
      protocol: PLAINTEXT

nais:
  token:
    endpoint: http://localhost:4100/api/v1/token
    exchange:
      endpoint: http://localhost:4100/api/v1/token/exchange

app:
  gruppe:
    saksbehandler: gr_saksbehandler
    attestant: gr_attestant
    les: gr_les
    drift: gr_drift
  pdl:
    audience: api://mock.pdl.pdl-api/.default
    url: http://localhost:9080/pdl-mock
  tilgangsmaskin:
    url: http://localhost:9080/tilgangsmaskin-mock
    audience: api://mock.tilgangsmaskin/.default
  pdfgen:
    url: http://localhost:8086
  dokarkiv:
    url: http://localhost:9080/dokarkiv-mock
    audience: api://mock.dokarkiv/.default
  saf:
    url: http://localhost:9080/saf-mock
    audience: api://mock.saf/.default
  dokdist:
    url: http://localhost:9080/dokdist-mock
    audience: api://mock.dokdist/.default
  oppgave:
    url: http://localhost:9080/oppgave-mock
    audience: api://mock.oppgave/.default
  entra-proxy:
    url: http://localhost:9080/entra-proxy-mock
    audience: api://mock.entra-proxy/.default
  kabal:
    url: http://localhost:9080/kabal-mock
    audience: api://mock.kabal/.default
    behandling-event-topic: klage.behandling-events.v1
  ereg:
    url: http://localhost:9080/ereg-mock
    audience: api://mock.ereg-services/.default
  infotrygd:
    url: http://localhost:9080/infotrygd-mock
    audience: api://mock.infotrygd/.default
