app:
  pdl:
    behandlingsnummer: B986
  utbetaling:
    utbetaling-topic: historisk.utbetaling.v1
    status-topic: helved.status.v1
  statistikk:
    # todo rette opp navn når vi det er testet
    saks-behandling-statistikk-topic: historisk.superhelt.statistikk.saksbehandling.test

info:
  nais:
    app: ${NAIS_APP_NAME:superhelt}
    image: ${NAIS_APP_IMAGE}
    cluster: ${NAIS_CLUSTER_NAME}

spring:
  application:
    name: superhelt
  http:
    clients:
      connect-timeout: 1s
      read-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
  web:
    resources:
      static-locations:
        - classpath:/static


  datasource:
    url: ${DB_JDBC_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SSL
    ssl:
      trust-store-type: JKS
      trust-store-location: file:${KAFKA_TRUSTSTORE_PATH}
      trust-store-password: ${KAFKA_CREDSTORE_PASSWORD}
      key-store-type: PKCS12
      key-store-location: file:${KAFKA_KEYSTORE_PATH}
      key-store-password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: tx-

    consumer:
      group-id: ${spring.application.name}
  cache:
    caffeine:
      spec: maximumSize=5000,expireAfterWrite=20m
    cache-names: pdlCache,tilgangsmaskinCache

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
