// This file is auto-generated by @hey-api/openapi-ts

import { type Options, findSaker, createSak, findPerson, getUserInfo, getSakBySaksnummer, getPerson } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { FindSakerData, CreateSakData, CreateSakError, CreateSakResponse, FindPersonData, FindPersonError, FindPersonResponse, GetUserInfoData, GetSakBySaksnummerData, GetPersonData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const findSakerQueryKey = (options: Options<FindSakerData>) => createQueryKey('findSaker', options);

export const findSakerOptions = (options: Options<FindSakerData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await findSaker({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: findSakerQueryKey(options)
    });
};

export const createSakMutation = (options?: Partial<Options<CreateSakData>>): UseMutationOptions<CreateSakResponse, CreateSakError, Options<CreateSakData>> => {
    const mutationOptions: UseMutationOptions<CreateSakResponse, CreateSakError, Options<CreateSakData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSak({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const findPersonMutation = (options?: Partial<Options<FindPersonData>>): UseMutationOptions<FindPersonResponse, FindPersonError, Options<FindPersonData>> => {
    const mutationOptions: UseMutationOptions<FindPersonResponse, FindPersonError, Options<FindPersonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await findPerson({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserInfoQueryKey = (options?: Options<GetUserInfoData>) => createQueryKey('getUserInfo', options);

export const getUserInfoOptions = (options?: Options<GetUserInfoData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserInfo({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserInfoQueryKey(options)
    });
};

export const getSakBySaksnummerQueryKey = (options: Options<GetSakBySaksnummerData>) => createQueryKey('getSakBySaksnummer', options);

export const getSakBySaksnummerOptions = (options: Options<GetSakBySaksnummerData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSakBySaksnummer({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSakBySaksnummerQueryKey(options)
    });
};

export const getPersonQueryKey = (options: Options<GetPersonData>) => createQueryKey('getPerson', options);

export const getPersonOptions = (options: Options<GetPersonData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPerson({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPersonQueryKey(options)
    });
};