name: Build and Test reusable workflow
on:
  workflow_call:
    secrets:
      READER_TOKEN:
        required: true
        description: 'Token with read access to the repository'
    outputs:
      image:
        description: 'Docker image '
        value: ${{ jobs.build.outputs.image }}
      telemetry:
        description: 'Telemetry data'
        value: ${{ jobs.build.outputs.telemetry }}

jobs:
  build:
    name: "Bygg backend"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup
        with:
          node-auth-token: ${{ secrets.READER_TOKEN }}

      - name: Build artifacts
        run: mvn --batch-mode clean verify
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@45d352fb62fb52ccb5ff6cba22c047fa02b35321 #v0
        id: docker-build-push
        with:
          team: historisk
          docker_context: ./backend
