name: Create or update Kafka topics

on:
  push:
    branches:
      - main
    paths:
      - ".nais/app/topics.yaml"
      - ".github/workflows/kafka.yml"

jobs:
  create-kafka-topics-dev:
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/dev.json

  create-kafka-topics-prod:
    needs: create-kafka-topics-dev
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 #v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/prod.json
