name: Create or update Kafka topics

on:
  push:
    branches:
      - main
    paths:
      - ".nais/app/topics.yaml"
      - ".github/workflows/kafka.yml"

jobs:
  create-kafka-topics-dev:
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nais/deploy/actions/deploy@fa8ae01f11325be17c1aa6de23cfe921008e2072 #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/dev.json

  create-kafka-topics-prod:
    needs: create-kafka-topics-dev
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nais/deploy/actions/deploy@fa8ae01f11325be17c1aa6de23cfe921008e2072 #v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/prod.json
