name: Create or update Kafka topics

on:
  push:
    branches:
      - main
    paths:
      - ".nais/app/topics.yaml"
      - ".github/workflows/kafka.yml"

jobs:
  create-kafka-topics-dev:
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/dev.json

  create-kafka-topics-prod:
    needs: create-kafka-topics-dev
    permissions:
      contents: read
      id-token: write
    name: Create or update Kafka topics in prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 #v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app/topics.yaml
          VARS: .nais/prod.json
