name: "Manuell deploy til dev"

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write
  deploy_dev:
    needs:
      - build
    name: "Deploy til dev"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: deploy-backend-dev
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Deploy backend til dev-gcp
        uses: nais/deploy/actions/deploy@7ad7c2b833e1db74a80954e3ee6bb6ac060a8ae7 #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/backend.yaml
          VARS: .nais/dev.json
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
