name: "Manuell deploy til dev"

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
  deploy_dev:
    needs:
      - build
    name: "Deploy til dev"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Deploy backend til dev-gcp
        uses: nais/deploy/actions/deploy@437e4adfe270e3f1c98fd0eed7f86ecf0e0873db #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/backend.yaml
          VARS: .nais/dev.json
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}

