name: Submit dependency graph
on:
  push:
    branches:
      - main
    paths:
      - "pom.xml"
      - "**/pom.xml"
jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Submit Dependency Snapshot (for dependabot)
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5