name: Bygg og deploy pdfgen

on:
  push:
    branches:
      - main
    paths:
      - 'pdfgen/**'
      - '.nais/app/pdfgen.yaml'
      - '.github/workflows/pdfgen.yml'

jobs:
  build:
    name: "Bygg pdfgen"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Verify: curl -s https://api.github.com/repos/nais/docker-build-push/git/refs/tags/v0 | jq -r '.object.sha'
      - name: Bygg og push docker image til GAR
        uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b #v0
        id: docker-build-push
        with:
          team: historisk
          docker_context: ./pdfgen

  deploy_dev:
    needs: [build]
    name: "Deploy til dev"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Verify: curl -s https://api.github.com/repos/nais/deploy/git/refs/tags/v2 | jq -r '.object.sha'
      - name: Deploy pdfgen til dev-gcp
        uses: nais/deploy/actions/deploy@437e4adfe270e3f1c98fd0eed7f86ecf0e0873db #v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app/pdfgen.yaml
          VARS: .nais/dev.json
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}

  deploy_prod:
    needs: [build, deploy_dev]
    name: "Deploy til prod"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Verify: curl -s https://api.github.com/repos/nais/deploy/git/refs/tags/v2 | jq -r '.object.sha'
      - name: Deploy pdfgen til prod-gcp
        uses: nais/deploy/actions/deploy@437e4adfe270e3f1c98fd0eed7f86ecf0e0873db #v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app/pdfgen.yaml
          VARS: .nais/prod.json
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
